default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

local: &local
  username: postgres
  password:

production:
  <<: *default
  database: pokeka_dex_api

development:
  <<: *default
  <<: *local
  database: pokeka_dex_api_dev

test:
  <<: *default
  <<: *local
  database: pokeka_dex_api_test
